In [1]:
import numpy as np

In [2]:
? np

Type:        module
String form: <module 'numpy' from 'C:\\Users\\Philip\\mambaforge\\lib\\site-packages\\numpy\\__init__.py'>
File:        c:\users\philip\mambaforge\lib\site-packages\numpy\__init__.py
Docstring:  
NumPy
=====

Provides
  1. An array object of arbitrary homogeneous items
  2. Fast mathematical operations over arrays
  3. Linear Algebra, Fourier Transforms, Random Number Generation

How to use the documentation
----------------------------
Documentation is available in two forms: docstrings provided
with the code, and a loose standing reference guide, available from
`the NumPy homepage <https://numpy.org>`_.

We recommend exploring the docstrings using
`IPython <https://ipython.org>`_, an advanced Python shell with
TAB-completion and introspection capabilities.  See below for further
instructions.

The docstring examples assume that `numpy` has been imported as ``np``::

  >>> import numpy as np

Code snippets are indicated by three greater-than signs::

  >>> x = 42
 

In [3]:
dir(np)

['ALLOW_THREADS',
 'AxisError',
 'BUFSIZE',
 'CLIP',
 'ComplexWarning',
 'DataSource',
 'ERR_CALL',
 'ERR_DEFAULT',
 'ERR_IGNORE',
 'ERR_LOG',
 'ERR_PRINT',
 'ERR_RAISE',
 'ERR_WARN',
 'FLOATING_POINT_SUPPORT',
 'FPE_DIVIDEBYZERO',
 'FPE_INVALID',
 'FPE_OVERFLOW',
 'FPE_UNDERFLOW',
 'False_',
 'Inf',
 'Infinity',
 'MAXDIMS',
 'MAY_SHARE_BOUNDS',
 'MAY_SHARE_EXACT',
 'ModuleDeprecationWarning',
 'NAN',
 'NINF',
 'NZERO',
 'NaN',
 'PINF',
 'PZERO',
 'RAISE',
 'RankWarning',
 'SHIFT_DIVIDEBYZERO',
 'SHIFT_INVALID',
 'SHIFT_OVERFLOW',
 'SHIFT_UNDERFLOW',
 'ScalarType',
 'Tester',
 'TooHardError',
 'True_',
 'UFUNC_BUFSIZE_DEFAULT',
 'UFUNC_PYVALS_NAME',
 'VisibleDeprecationWarning',
 'WRAP',
 '_CopyMode',
 '_NoValue',
 '_UFUNC_API',
 '__NUMPY_SETUP__',
 '__all__',
 '__builtins__',
 '__cached__',
 '__config__',
 '__deprecated_attrs__',
 '__dir__',
 '__doc__',
 '__expired_functions__',
 '__file__',
 '__future_scalars__',
 '__getattr__',
 '__git_version__',
 '__loader__',
 '__name__',
 '__pac

In [6]:
np.__name__

'numpy'

In [4]:
np.__version__

'1.24.1'

In [5]:
np.__path__

['C:\\Users\\Philip\\mambaforge\\lib\\site-packages\\numpy']

In [9]:
np.cos

<ufunc 'cos'>

In [10]:
? np.math

Type:        module
String form: <module 'math' (built-in)>
Docstring:  
This module provides access to the mathematical functions
defined by the C standard.

In [11]:
np.char

<module 'numpy.core.defchararray' from 'C:\\Users\\Philip\\mambaforge\\lib\\site-packages\\numpy\\core\\defchararray.py'>

In [12]:
np.compat

<module 'numpy.compat' from 'C:\\Users\\Philip\\mambaforge\\lib\\site-packages\\numpy\\compat\\__init__.py'>

In [13]:
np.ctypeslib

<module 'numpy.ctypeslib' from 'C:\\Users\\Philip\\mambaforge\\lib\\site-packages\\numpy\\ctypeslib.py'>

In [15]:
? np.emath

Type:        module
String form: <module 'numpy.lib.scimath' from 'C:\\Users\\Philip\\mambaforge\\lib\\site-packages\\numpy\\lib\\scimath.py'>
File:        c:\users\philip\mambaforge\lib\site-packages\numpy\lib\scimath.py
Docstring:  
Wrapper functions to more user-friendly calling of certain math functions
whose output data-type is different than the input data-type in certain
domains of the input.

For example, for functions like `log` with branch cuts, the versions in this
module provide the mathematically valid answers in the complex plane::

  >>> import math
  >>> np.emath.log(-math.exp(1)) == (1+1j*math.pi)
  True

Similarly, `sqrt`, other base logarithms, `power` and trig functions are
correctly handled.  See their respective docstrings for specific examples.

Functions
---------

.. autosummary::
   :toctree: generated/

   sqrt
   log
   log2
   logn
   log10
   power
   arccos
   arcsin
   arctanh

In [16]:
np.lib

<module 'numpy.lib' from 'C:\\Users\\Philip\\mambaforge\\lib\\site-packages\\numpy\\lib\\__init__.py'>

In [17]:
np.linalg

<module 'numpy.linalg' from 'C:\\Users\\Philip\\mambaforge\\lib\\site-packages\\numpy\\linalg\\__init__.py'>

In [18]:
np.ma

<module 'numpy.ma' from 'C:\\Users\\Philip\\mambaforge\\lib\\site-packages\\numpy\\ma\\__init__.py'>

In [19]:
np.polynomial

<module 'numpy.polynomial' from 'C:\\Users\\Philip\\mambaforge\\lib\\site-packages\\numpy\\polynomial\\__init__.py'>

In [20]:
np.testing

<module 'numpy.testing' from 'C:\\Users\\Philip\\mambaforge\\lib\\site-packages\\numpy\\testing\\__init__.py'>

In [21]:
np.version

<module 'numpy.version' from 'C:\\Users\\Philip\\mambaforge\\lib\\site-packages\\numpy\\version.py'>

In [30]:
np.array([1, 2, 3, 4, 5])

array([1, 2, 3, 4, 5])

In [32]:
? np.ndarray

Init signature:  np.ndarray(self, /, *args, **kwargs)
Docstring:     
ndarray(shape, dtype=float, buffer=None, offset=0,
        strides=None, order=None)

An array object represents a multidimensional, homogeneous array
of fixed-size items.  An associated data-type object describes the
format of each element in the array (its byte-order, how many bytes it
occupies in memory, whether it is an integer, a floating point number,
or something else, etc.)

Arrays should be constructed using `array`, `zeros` or `empty` (refer
to the See Also section below).  The parameters given here refer to
a low-level method (`ndarray(...)`) for instantiating an array.

For more information, refer to the `numpy` module and examine the
methods and attributes of an array.

Parameters
----------
(for the __new__ method; see Notes below)

shape : tuple of ints
    Shape of created array.
dtype : data-type, optional
    Any object that can be interpreted as a numpy data type.
buffer : object exposing buffer in

In [51]:
list1 = [1, 2, 3, 4]

In [54]:
array1 = np.asarray(a=list1, dtype=int)
array1

array([1, 2, 3, 4])

In [57]:
array1.shape

(4,)

In [58]:
array1.size

4

In [59]:
array1.dtype

dtype('int32')

In [56]:
array2 = np.array(object=[1, 2, 3, 4, 5], dtype=int)
array2

array([1, 2, 3, 4, 5])

In [61]:
array2.shape

(5,)

In [62]:
array2.size

5

In [63]:
array2.dtype

dtype('int32')

In [60]:
array3 = np.array([1, 2, 3, 4, 5])
array3

array([1, 2, 3, 4, 5])

In [79]:
array4 = np.empty(shape=(6,), dtype=float)
array4

array([4., 4., 4., 4., 4., 4.])

In [67]:
array5 = np.empty_like(prototype=array3, dtype=int)
array5

array([-405262112,        606,          0,          0,          1])

In [78]:
array6 = np.zeros(shape=(6,), dtype=int)
array6

array([0, 0, 0, 0, 0, 0])

In [74]:
array7 = np.zeros_like(a=array3, dtype=int)
array7

array([0, 0, 0, 0, 0])

In [77]:
array8 = np.ones(shape=(6,), dtype=int)
array8

array([1, 1, 1, 1, 1, 1])

In [76]:
array9 = np.ones_like(a=array3, dtype=int)
array9

array([1, 1, 1, 1, 1])

In [83]:
array10 = np.full(shape=(6,), fill_value=4.0, dtype=float)
array10

array([4., 4., 4., 4., 4., 4.])

In [86]:
array11 = np.full_like(a=array3, fill_value=4.0, dtype=float)
array11

array([4., 4., 4., 4., 4.])

In [89]:
array12 = np.array(object=range(0, 5, 1), dtype=int)
array12

array([0, 1, 2, 3, 4])

In [91]:
array13 = np.arange(start=0, stop=5, step=1, dtype=int)
array13

array([0, 1, 2, 3, 4])

In [93]:
array14 = np.array(object=range(0, 5, 0.1), dtype=float)
array14

TypeError: 'float' object cannot be interpreted as an integer

In [94]:
array15 = np.arange(start=0, stop=5, step=0.1, dtype=float)
array15

array([0. , 0.1, 0.2, 0.3, 0.4, 0.5, 0.6, 0.7, 0.8, 0.9, 1. , 1.1, 1.2,
       1.3, 1.4, 1.5, 1.6, 1.7, 1.8, 1.9, 2. , 2.1, 2.2, 2.3, 2.4, 2.5,
       2.6, 2.7, 2.8, 2.9, 3. , 3.1, 3.2, 3.3, 3.4, 3.5, 3.6, 3.7, 3.8,
       3.9, 4. , 4.1, 4.2, 4.3, 4.4, 4.5, 4.6, 4.7, 4.8, 4.9])

In [95]:
array16 = np.arange(start=0, stop=5+0.1, step=0.1, dtype=float)
array16

array([0. , 0.1, 0.2, 0.3, 0.4, 0.5, 0.6, 0.7, 0.8, 0.9, 1. , 1.1, 1.2,
       1.3, 1.4, 1.5, 1.6, 1.7, 1.8, 1.9, 2. , 2.1, 2.2, 2.3, 2.4, 2.5,
       2.6, 2.7, 2.8, 2.9, 3. , 3.1, 3.2, 3.3, 3.4, 3.5, 3.6, 3.7, 3.8,
       3.9, 4. , 4.1, 4.2, 4.3, 4.4, 4.5, 4.6, 4.7, 4.8, 4.9, 5. ])

In [99]:
array17 = np.linspace(start=0, stop=5, num=11)
array17

array([0. , 0.5, 1. , 1.5, 2. , 2.5, 3. , 3.5, 4. , 4.5, 5. ])

In [104]:
array17

array([0. , 0.5, 1. , 1.5, 2. , 2.5, 3. , 3.5, 4. , 4.5, 5. ])

In [103]:
array17.size

11

In [102]:
array17.shape

(11,)

In [113]:
array17.shape[0]

11

In [114]:
array17.shape[-1]

11

In [112]:
array17[0:array17.shape[0]:1]

array([0. , 0.5, 1. , 1.5, 2. , 2.5, 3. , 3.5, 4. , 4.5, 5. ])

In [128]:
array18 = array17[np.newaxis, :]
array18

array([[0. , 0.5, 1. , 1.5, 2. , 2.5, 3. , 3.5, 4. , 4.5, 5. ]])

In [129]:
array18.shape

(1, 11)

In [130]:
array18_nrows = array18.shape[0]
array18_nrows

1

In [131]:
array18_ncols = array18.shape[1]
array18_ncols

11

In [135]:
array18.shape

(1, 11)

In [133]:
array18_ncols = array18.shape[-1]
array18_ncols

11

In [134]:
array18_nrows = array18.shape[-2]
array18_nrows

1

In [137]:
array19 = array17[:, np.newaxis]
array19

array([[0. ],
       [0.5],
       [1. ],
       [1.5],
       [2. ],
       [2.5],
       [3. ],
       [3.5],
       [4. ],
       [4.5],
       [5. ]])

In [138]:
array19.shape

(11, 1)

In [139]:
array19_ncols = array19.shape[-1]
array19_ncols

1

In [140]:
array19_nrows = array19.shape[-2]
array19_nrows

11

In [144]:
array20 = np.array([[1, 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12]])
array20

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [145]:
array20 = np.array([[1, 2, 3, 4], 
                    [5, 6, 7, 8], 
                    [9, 10, 11, 12]])
array20

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [146]:
array20.shape

(3, 4)

In [149]:
array20_ncols = array20.shape[-1]
array20_ncols

4

In [148]:
array20_nrows = array20.shape[-2]
array20_nrows

3

In [150]:
array21 = np.arange(start=1, stop=12+1, step=1)
array21

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12])

In [151]:
array21.size

12

In [152]:
array21.shape

(12,)

In [156]:
array21.reshape(shape=(3, 4))

TypeError: 'shape' is an invalid keyword argument for this function

In [158]:
array22 = array21.reshape((3, 4))
array22

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [159]:
array23 = array21.reshape(3, 4)
array23

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [162]:
# FORTRAN (column major) or C (row major) 

In [161]:
array25 = array21.reshape(3, 4, order='C')
array25

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [163]:
array26 = array21.reshape(3, 4, order='F')
array26

array([[ 1,  4,  7, 10],
       [ 2,  5,  8, 11],
       [ 3,  6,  9, 12]])

In [179]:
array25

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [180]:
array25.size

12

In [181]:
array25.shape

(3, 4)

In [182]:
array25_ncols = array25.shape[-1]
array25_ncols

4

In [183]:
array25_nrows = array25.shape[-2]
array25_nrows

3

In [184]:
array25[::][::]

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [186]:
array25[::, ::]

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [187]:
array25[::, 0:array25_ncols:1]

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [188]:
array25[0:array25_nrows:1, ::]

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [191]:
array25[0:2, 2:4]

array([[3, 4],
       [7, 8]])

In [193]:
array25[[0, 2], 2:4]

array([[ 3,  4],
       [11, 12]])

In [194]:
array25[[0, 2], 3]

array([ 4, 12])

In [195]:
array25[[0, 2], [1, 3]]

array([ 2, 12])

In [198]:
array27 = np.identity(n=3)
array27

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [200]:
array28 = np.eye(N=3, M=3, k=0)
array28

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [201]:
array29 = np.eye(N=3, M=3, k=1)
array29

array([[0., 1., 0.],
       [0., 0., 1.],
       [0., 0., 0.]])

In [202]:
array30 = np.eye(N=3, M=3, k=-1)
array30

array([[0., 0., 0.],
       [1., 0., 0.],
       [0., 1., 0.]])

In [207]:
import numpy.random as random

In [208]:
dir(random)

['BitGenerator',
 'Generator',
 'MT19937',
 'PCG64',
 'PCG64DXSM',
 'Philox',
 'RandomState',
 'SFC64',
 'SeedSequence',
 '__RandomState_ctor',
 '__all__',
 '__builtins__',
 '__cached__',
 '__doc__',
 '__file__',
 '__loader__',
 '__name__',
 '__package__',
 '__path__',
 '__spec__',
 '_bounded_integers',
 '_common',
 '_generator',
 '_mt19937',
 '_pcg64',
 '_philox',
 '_pickle',
 '_sfc64',
 'beta',
 'binomial',
 'bit_generator',
 'bytes',
 'chisquare',
 'choice',
 'default_rng',
 'dirichlet',
 'exponential',
 'f',
 'gamma',
 'geometric',
 'get_bit_generator',
 'get_state',
 'gumbel',
 'hypergeometric',
 'laplace',
 'logistic',
 'lognormal',
 'logseries',
 'mtrand',
 'multinomial',
 'multivariate_normal',
 'negative_binomial',
 'noncentral_chisquare',
 'noncentral_f',
 'normal',
 'pareto',
 'permutation',
 'poisson',
 'power',
 'rand',
 'randint',
 'randn',
 'random',
 'random_integers',
 'random_sample',
 'ranf',
 'rayleigh',
 'sample',
 'seed',
 'set_bit_generator',
 'set_state',
 'shuf

In [217]:
random.seed(0)

In [218]:
array31 = random.randint(low=0, high=10, size=5)
array31

array([5, 0, 3, 3, 7])

In [219]:
array32 = random.randint(low=0, high=10, size=(3, 5))
array32

array([[9, 3, 5, 2, 4],
       [7, 6, 8, 8, 1],
       [6, 7, 7, 8, 1]])

In [220]:
array33 = random.randint(low=0, high=10, size=(2, 3, 5))
array33

array([[[5, 9, 8, 9, 4],
        [3, 0, 3, 5, 0],
        [2, 3, 8, 1, 3]],

       [[3, 3, 7, 0, 1],
        [9, 9, 0, 4, 7],
        [3, 2, 7, 2, 0]]])

In [222]:
array33.size

30

In [223]:
array33.shape

(2, 3, 5)

In [224]:
array33_ncols = array33.shape[-1]
array33_ncols

5

In [225]:
array33_nrows = array33.shape[-2]
array33_nrows

3

In [226]:
array33_npages = array33.shape[-3]
array33_npages

2

In [227]:
array33

array([[[5, 9, 8, 9, 4],
        [3, 0, 3, 5, 0],
        [2, 3, 8, 1, 3]],

       [[3, 3, 7, 0, 1],
        [9, 9, 0, 4, 7],
        [3, 2, 7, 2, 0]]])

In [228]:
array33[0, 1, 3]

5

In [230]:
array34 = random.randint(low=0, high=10, size=(2, 2, 3, 5))
array34

array([[[[5, 7, 8, 8, 9],
         [2, 8, 6, 6, 9],
         [1, 6, 8, 8, 3]],

        [[2, 3, 6, 3, 6],
         [5, 7, 0, 8, 4],
         [6, 5, 8, 2, 3]]],


       [[[9, 7, 5, 3, 4],
         [5, 3, 3, 7, 9],
         [9, 9, 7, 3, 2]],

        [[3, 9, 7, 7, 5],
         [1, 2, 2, 8, 1],
         [5, 8, 4, 0, 2]]]])

In [232]:
array34.size

60

In [233]:
array34.shape

(2, 2, 3, 5)

In [234]:
array34_ncols = array34.shape[-1]
array34_ncols

5

In [235]:
array34_nrows = array34.shape[-2]
array34_nrows

3

In [236]:
array34_npages = array34.shape[-3]
array34_npages

2

In [237]:
array34_nbooks = array34.shape[-4]
array34_nbooks

2

In [239]:
array35 = random.randint(low=0, high=10, size=(3, 2, 2, 3, 5))
#array35

In [240]:
array35_ncols = array35.shape[-1]
array35_ncols

5

In [241]:
array35_ncols = array35.shape[-2]
array35_ncols

3

In [242]:
array35_npages = array35.shape[-3]
array35_npages

2

In [243]:
array35_nbooks = array35.shape[-4]
array35_nbooks

2

In [244]:
array35_nshelves = array35.shape[-5]
array35_nshelves

3

In [ ]:
#nbookstands
#nlibraries