In [1]:
import numpy as np

In [2]:
np.__name__

'numpy'

In [3]:
np.__version__

'1.24.1'

In [4]:
np.__path__

['C:\\Users\\AppsLab\\mambaforge\\envs\\jupyterlab-cf\\Lib\\site-packages\\numpy']

In [5]:
? np.ndarray

Init signature:  np.ndarray(self, /, *args, **kwargs)
Docstring:     
ndarray(shape, dtype=float, buffer=None, offset=0,
        strides=None, order=None)

An array object represents a multidimensional, homogeneous array
of fixed-size items.  An associated data-type object describes the
format of each element in the array (its byte-order, how many bytes it
occupies in memory, whether it is an integer, a floating point number,
or something else, etc.)

Arrays should be constructed using `array`, `zeros` or `empty` (refer
to the See Also section below).  The parameters given here refer to
a low-level method (`ndarray(...)`) for instantiating an array.

For more information, refer to the `numpy` module and examine the
methods and attributes of an array.

Parameters
----------
(for the __new__ method; see Notes below)

shape : tuple of ints
    Shape of created array.
dtype : data-type, optional
    Any object that can be interpreted as a numpy data type.
buffer : object exposing buffer in

In [6]:
? np.array

Docstring:
array(object, dtype=None, *, copy=True, order='K', subok=False, ndmin=0,
      like=None)

Create an array.

Parameters
----------
object : array_like
    An array, any object exposing the array interface, an object whose
    __array__ method returns an array, or any (nested) sequence.
    If object is a scalar, a 0-dimensional array containing object is
    returned.
dtype : data-type, optional
    The desired data-type for the array.  If not given, then the type will
    be determined as the minimum type required to hold the objects in the
    sequence.
copy : bool, optional
    If true (default), then the object is copied.  Otherwise, a copy will
    only be made if __array__ returns a copy, if obj is a nested sequence,
    or if a copy is needed to satisfy any of the other requirements
    (`dtype`, `order`, etc.).
order : {'K', 'A', 'C', 'F'}, optional
    Specify the memory layout of the array. If object is not an array, the
    newly created array will be in C order (

In [7]:
list1 = [1, 2, 3, 4]
list1

[1, 2, 3, 4]

In [8]:
list1 = [1, 
         2, 
         3, 
         4]
list1

[1, 2, 3, 4]

In [9]:
array1 = np.array(object=[1, 2, 3, 4])
array1

array([1, 2, 3, 4])

In [10]:
arrayr = np.array([1, 2, 3, 4], ndmin=2)
arrayr

array([[1, 2, 3, 4]])

In [11]:
arrayr.size

4

In [12]:
arrayr.ndim

2

In [13]:
arrayr.shape

(1, 4)

In [14]:
array1.ndim

1

In [15]:
array1.shape

(4,)

In [16]:
arrayr.ndim

2

In [17]:
arrayr.shape

(1, 4)

In [18]:
column = [1, 2, 3, 4]

In [19]:
row = [column]
row

[[1, 2, 3, 4]]

In [20]:
array1_cols = array1.shape[0]
array1_cols

4

In [21]:
arrayr_rows = arrayr.shape[0]
arrayr_rows

1

In [22]:
arrayr_cols = arrayr.shape[1]
arrayr_cols

4

In [23]:
array1_cols = array1.shape[-1]
array1_cols

4

In [24]:
arrayr_rows = arrayr.shape[-1]
arrayr_rows

4

In [25]:
arrayr_cols = arrayr.shape[-2]
arrayr_cols

1

In [26]:
arrayc = np.array([1, 2, 3, 4], ndmin=2).T
arrayc

array([[1],
       [2],
       [3],
       [4]])

In [27]:
arrayc.size

4

In [28]:
arrayc.ndim

2

In [29]:
arrayc.shape

(4, 1)

In [30]:
array1.shape

(4,)

In [31]:
arrayr.shape

(1, 4)

In [32]:
arrayr.size

4

In [33]:
arrayr.ndim

2

In [34]:
arrayr.shape

(1, 4)

In [35]:
array1 = np.array([1, 2, 3, 4])
array1

array([1, 2, 3, 4])

In [36]:
array1.dtype

dtype('int32')

In [37]:
array1 = np.array([1., 2, 3, 4])
array1

array([1., 2., 3., 4.])

In [38]:
array1.dtype

dtype('float64')

In [39]:
array1 = np.array([1+2j, 2, 3, 4])
array1

array([1.+2.j, 2.+0.j, 3.+0.j, 4.+0.j])

In [40]:
array1.dtype

dtype('complex128')

In [41]:
array1 = np.array([True, False, False, False])
array1

array([ True, False, False, False])

In [42]:
array1.dtype

dtype('bool')

In [43]:
array1 = np.array([1, 2, 3, 4], dtype=float)
array1

array([1., 2., 3., 4.])

In [44]:
array1.dtype

dtype('float64')

In [45]:
matrix1 = np.array([[1, 2, 3],
                    [4, 5, 6]])
matrix1

array([[1, 2, 3],
       [4, 5, 6]])

In [46]:
matrix1.size

6

In [47]:
matrix1.ndim

2

In [48]:
matrix1.shape

(2, 3)

In [49]:
matrix2 = np.empty_like(prototype=matrix1)
matrix2

array([[206415136,       558,         0],
       [        0,         1,     32767]])

In [50]:
matrix3 = np.zeros_like(a=matrix1)
matrix3

array([[0, 0, 0],
       [0, 0, 0]])

In [51]:
matrix4 = np.ones_like(a=matrix1)
matrix4

array([[1, 1, 1],
       [1, 1, 1]])

In [52]:
matrix5 = np.full_like(a=matrix1, fill_value=2)
matrix5

array([[2, 2, 2],
       [2, 2, 2]])

In [53]:
matrix2 = np.empty(shape=(4, 3))
matrix2

array([[1.18416468e-311, 3.16202013e-322, 0.00000000e+000],
       [0.00000000e+000, 1.08221785e-312, 4.32040381e-061],
       [4.23105086e+175, 8.32377570e-071, 8.69895165e-043],
       [1.09773320e-071, 8.16292206e-043, 1.65820524e-076]])

In [54]:
matrix3 = np.zeros(shape=(4, 3))
matrix3

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [55]:
matrix4 = np.ones(shape=(4, 3))
matrix4

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [56]:
matrix5 = np.full(shape=(4, 3), fill_value=4)
matrix5

array([[4, 4, 4],
       [4, 4, 4],
       [4, 4, 4],
       [4, 4, 4]])

In [57]:
book1 = np.array([[[1, 2,], 
                   [3, 4]],
                  
                  [[5, 6], 
                   [7, 8]],
                  
                  [[9, 10], 
                   [11, 12]]])
book1

array([[[ 1,  2],
        [ 3,  4]],

       [[ 5,  6],
        [ 7,  8]],

       [[ 9, 10],
        [11, 12]]])

In [58]:
book1.size

12

In [59]:
book1.ndim

3

In [60]:
book1.shape

(3, 2, 2)

In [61]:
it = book1.flat
it

In [62]:
next(it)

1

In [63]:
next(it)

2

In [64]:
next(it)

3

In [65]:
next(it)

4

In [66]:
next(it)

5

In [67]:
list(it)

[6, 7, 8, 9, 10, 11, 12]

In [68]:
it = book1.flat
it

In [69]:
array1 = np.array(list(it))
array1

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12])

In [70]:
book1.flatten()

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12])

In [71]:
array1 = book1.ravel()
array1

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12])

In [72]:
array1 = np.ravel(book1)
array1

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12])

In [73]:
booklist1 = [[[1, 2,], 
              [3, 4]],
                  
              [[5, 6], 
               [7, 8]],
                  
              [[9, 10], 
               [11, 12]]]

booklist1

[[[1, 2], [3, 4]], [[5, 6], [7, 8]], [[9, 10], [11, 12]]]

In [74]:
array1 = np.ravel(booklist1)
array1

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12])

In [75]:
list(array1)

[1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12]

In [76]:
array1.tolist()

[1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12]

In [77]:
booklist1 = [[[1, 2,], 
              [3, 4]],
                  
              [[5, 6], 
               [7, 8]],
                  
              [[9, 10], 
               [11, 12]]]

booklist1

[[[1, 2], [3, 4]], [[5, 6], [7, 8]], [[9, 10], [11, 12]]]

In [78]:
np.ravel(booklist1, order='F')

array([ 1,  5,  9,  3,  7, 11,  2,  6, 10,  4,  8, 12])

In [79]:
matrix1 = np.reshape(a=book1, newshape=(4, 3))
matrix1

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [10, 11, 12]])

In [80]:
matrix1 = book1.reshape((4,3))
matrix1

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [10, 11, 12]])

In [81]:
matrixlist1 = [[1, 2, 3],
               [4, 5, 6],
               [7, 8, 9],
               [10, 11, 12]]

In [82]:
row0 = [1, 2, 3]

In [83]:
row1 = [4, 5, 6]

In [84]:
row2 = [7, 8, 9]

In [85]:
row3 = [10, 11, 12]

In [86]:
matrixlist1 = [row0,
               row1,
               row2,
               row3]

In [87]:
matrixlist1[0]

[1, 2, 3]

In [88]:
matrixlist1[0][1]

2

In [89]:
matrix1 = np.array([[1, 2, 3],
                    [4, 5, 6],
                    [7, 8, 9],
                    [10, 11, 12]])

In [90]:
matrix1[0][1]

2

In [91]:
matrix1[0, 1]

2

In [92]:
matrix1[[0, 1], [1, 0]]

array([2, 4])

In [93]:
matrix1[[0, 0, 0], [0, 1, 2]]

array([1, 2, 3])

In [94]:
matrix1[0, [0, 1, 2]]

array([1, 2, 3])

In [95]:
matrix1[0, 0:matrix1.shape[1]:1]

array([1, 2, 3])

In [96]:
matrix1[0, ::]

array([1, 2, 3])

In [97]:
matrix1[0, :]

array([1, 2, 3])

In [98]:
matrix1[0, -1:-matrix1.shape[1]-1:-1]

array([3, 2, 1])

In [99]:
matrix1[0, ::-1]

array([3, 2, 1])

In [100]:
matrix1_lr = matrix1[:, ::-1]
matrix1_lr

array([[ 3,  2,  1],
       [ 6,  5,  4],
       [ 9,  8,  7],
       [12, 11, 10]])

In [101]:
matrix1_lr = np.fliplr(m=matrix1)
matrix1_lr

array([[ 3,  2,  1],
       [ 6,  5,  4],
       [ 9,  8,  7],
       [12, 11, 10]])

In [102]:
matrix1_lr = np.flip(m=matrix1, axis=1)
matrix1_lr

array([[ 3,  2,  1],
       [ 6,  5,  4],
       [ 9,  8,  7],
       [12, 11, 10]])

In [103]:
matrix1_lr = np.flip(m=matrix1, axis=-1)
matrix1_lr

array([[ 3,  2,  1],
       [ 6,  5,  4],
       [ 9,  8,  7],
       [12, 11, 10]])

In [104]:
matrix1_ud = matrix1[::-1, :]
matrix1_ud

array([[10, 11, 12],
       [ 7,  8,  9],
       [ 4,  5,  6],
       [ 1,  2,  3]])

In [105]:
matrix1_ud = np.flipud(m=matrix1)
matrix1_ud

array([[10, 11, 12],
       [ 7,  8,  9],
       [ 4,  5,  6],
       [ 1,  2,  3]])

In [106]:
matrix1_ud = np.flip(m=matrix1, axis=-2)
matrix1_ud

array([[10, 11, 12],
       [ 7,  8,  9],
       [ 4,  5,  6],
       [ 1,  2,  3]])

In [107]:
arrayr = np.array([1, 2, 3, 4], ndmin=2)
arrayr

array([[1, 2, 3, 4]])

In [108]:
arrayc = arrayr.T
arrayc

array([[1],
       [2],
       [3],
       [4]])

In [109]:
arrayr = arrayc.T
arrayr

array([[1, 2, 3, 4]])

In [110]:
arrayc = np.transpose(arrayr)
arrayc

array([[1],
       [2],
       [3],
       [4]])

In [111]:
matrix1

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [10, 11, 12]])

In [112]:
matrix1_t = matrix1.T
matrix1_t

array([[ 1,  4,  7, 10],
       [ 2,  5,  8, 11],
       [ 3,  6,  9, 12]])

In [113]:
book = np.zeros(shape=(3, 4, 3))
book

array([[[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]]])

In [114]:
book.size

36

In [115]:
book.ndim

3

In [116]:
book.shape

(3, 4, 3)

In [117]:
page0 = np.array([[1, 2, 3],
                  [4, 5, 6],
                  [7, 8, 9],
                  [10, 11, 12]])
page0

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [10, 11, 12]])

In [118]:
page0.size

12

In [119]:
page0.ndim

2

In [120]:
page0.shape

(4, 3)

In [121]:
page1 = np.array([[13, 14, 15],
                  [16, 17, 18],
                  [19, 20, 21],
                  [22, 23, 24]])
page1

array([[13, 14, 15],
       [16, 17, 18],
       [19, 20, 21],
       [22, 23, 24]])

In [122]:
page2 = np.array([[25, 26, 27],
                  [28, 29, 30],
                  [31, 32, 33],
                  [34, 35, 36]])
page2

array([[25, 26, 27],
       [28, 29, 30],
       [31, 32, 33],
       [34, 35, 36]])

In [123]:
book[0, :, :] = page0
book

array([[[ 1.,  2.,  3.],
        [ 4.,  5.,  6.],
        [ 7.,  8.,  9.],
        [10., 11., 12.]],

       [[ 0.,  0.,  0.],
        [ 0.,  0.,  0.],
        [ 0.,  0.,  0.],
        [ 0.,  0.,  0.]],

       [[ 0.,  0.,  0.],
        [ 0.,  0.,  0.],
        [ 0.,  0.,  0.],
        [ 0.,  0.,  0.]]])

In [124]:
book[0, :, :] = page1
book[0, :, :] = page2
book

array([[[25., 26., 27.],
        [28., 29., 30.],
        [31., 32., 33.],
        [34., 35., 36.]],

       [[ 0.,  0.,  0.],
        [ 0.,  0.,  0.],
        [ 0.,  0.,  0.],
        [ 0.,  0.,  0.]],

       [[ 0.,  0.,  0.],
        [ 0.,  0.,  0.],
        [ 0.,  0.,  0.],
        [ 0.,  0.,  0.]]])

In [125]:
array1 = np.array(object=range(0, 10, 1))
array1

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [126]:
array1.ndim

1

In [127]:
array1.size

10

In [128]:
array1.dtype

dtype('int32')

In [129]:
array1 = np.array(object=range(0, 10+1, 1))
array1

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [130]:
array1.ndim

1

In [131]:
array1.size

11

In [132]:
array1.dtype

dtype('int32')

In [133]:
#array1 = np.array(object=range(0.0, 10.0+0.1, 0.1))
#array1

In [134]:
array1 = np.arange(start=0, stop=10, step=1)
array1

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [135]:
array1.ndim

1

In [136]:
array1.size

10

In [137]:
array1.dtype

dtype('int32')

In [138]:
array1 = np.arange(start=0, stop=10+1, step=1)
array1

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [139]:
array1.ndim

1

In [140]:
array1.size

11

In [141]:
array1.dtype

dtype('int32')

In [142]:
array1 = np.arange(start=0.0, stop=10.0+0.1, step=0.1)
array1

array([ 0. ,  0.1,  0.2,  0.3,  0.4,  0.5,  0.6,  0.7,  0.8,  0.9,  1. ,
        1.1,  1.2,  1.3,  1.4,  1.5,  1.6,  1.7,  1.8,  1.9,  2. ,  2.1,
        2.2,  2.3,  2.4,  2.5,  2.6,  2.7,  2.8,  2.9,  3. ,  3.1,  3.2,
        3.3,  3.4,  3.5,  3.6,  3.7,  3.8,  3.9,  4. ,  4.1,  4.2,  4.3,
        4.4,  4.5,  4.6,  4.7,  4.8,  4.9,  5. ,  5.1,  5.2,  5.3,  5.4,
        5.5,  5.6,  5.7,  5.8,  5.9,  6. ,  6.1,  6.2,  6.3,  6.4,  6.5,
        6.6,  6.7,  6.8,  6.9,  7. ,  7.1,  7.2,  7.3,  7.4,  7.5,  7.6,
        7.7,  7.8,  7.9,  8. ,  8.1,  8.2,  8.3,  8.4,  8.5,  8.6,  8.7,
        8.8,  8.9,  9. ,  9.1,  9.2,  9.3,  9.4,  9.5,  9.6,  9.7,  9.8,
        9.9, 10. ])

In [143]:
array1.ndim

1

In [144]:
array1.size

101

In [145]:
array1.dtype

dtype('float64')

In [146]:
import datetime as dt

In [147]:
python3released = dt.datetime(year=2008, month=12, day=3, 
                              hour=12, minute=0, second=0, 
                              microsecond=0)
python3released

datetime.datetime(2008, 12, 3, 12, 0)

In [148]:
today = dt.datetime.now()
today

datetime.datetime(2023, 1, 23, 17, 39, 16, 699973)

In [149]:
day = dt.timedelta(days=1)
day

datetime.timedelta(days=1)

In [150]:
python3birthdays = np.arange(start=python3released, stop=today+day, step=day)
python3birthdays

array(['2008-12-03T12:00:00.000000', '2008-12-04T12:00:00.000000',
       '2008-12-05T12:00:00.000000', ..., '2023-01-22T12:00:00.000000',
       '2023-01-23T12:00:00.000000', '2023-01-24T12:00:00.000000'],
      dtype='datetime64[us]')

In [151]:
array1 = np.linspace(start=0, stop=10, num=11)
array1

array([ 0.,  1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10.])

In [152]:
array1.ndim

1

In [153]:
array1.size

11

In [154]:
array1.dtype

dtype('float64')

In [155]:
equations = np.array([[5, 6],
                      [3, 3]])
equations

array([[5, 6],
       [3, 3]])

In [156]:
results = np.array([83, 42])[:, np.newaxis]
results

array([[83],
       [42]])

In [157]:
inv_equations = np.linalg.inv(equations)
inv_equations

array([[-1.        ,  2.        ],
       [ 1.        , -1.66666667]])

In [158]:
inv_equations @ equations

array([[ 1.0000000e+00, -8.8817842e-16],
       [ 0.0000000e+00,  1.0000000e+00]])

In [159]:
equations @ inv_equations

array([[ 1.0000000e+00,  0.0000000e+00],
       [-4.4408921e-16,  1.0000000e+00]])

In [160]:
np.identity(n=2)

array([[1., 0.],
       [0., 1.]])

In [161]:
np.eye(N=2)

array([[1., 0.],
       [0., 1.]])

In [162]:
np.eye(N=2, M=3)

array([[1., 0., 0.],
       [0., 1., 0.]])

In [163]:
np.eye(N=3, M=3, k=0)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [164]:
np.eye(N=3, M=3, k=1)

array([[0., 1., 0.],
       [0., 0., 1.],
       [0., 0., 0.]])

In [165]:
np.eye(N=3, M=3, k=-1)

array([[0., 0., 0.],
       [1., 0., 0.],
       [0., 1., 0.]])

In [166]:
coefficients = inv_equations @ results
coefficients

array([[ 1.],
       [13.]])

In [167]:
coefficients = np.linalg.solve(equations, results)
coefficients

array([[ 1.],
       [13.]])

In [168]:
matrix1 = np.arange(start=1, stop=17, step=1).reshape((4, 4))
matrix1

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12],
       [13, 14, 15, 16]])

In [169]:
matrix1.diagonal()

array([ 1,  6, 11, 16])

In [170]:
np.diagonal(a=matrix1)

array([ 1,  6, 11, 16])

In [171]:
matrix1.diagonal(offset=1)

array([ 2,  7, 12])

In [172]:
matrix1.diagonal(offset=-1)

array([ 5, 10, 15])

In [173]:
book1 = np.arange(start=1, stop=65, step=1).reshape((4, 4, 4))
book1

array([[[ 1,  2,  3,  4],
        [ 5,  6,  7,  8],
        [ 9, 10, 11, 12],
        [13, 14, 15, 16]],

       [[17, 18, 19, 20],
        [21, 22, 23, 24],
        [25, 26, 27, 28],
        [29, 30, 31, 32]],

       [[33, 34, 35, 36],
        [37, 38, 39, 40],
        [41, 42, 43, 44],
        [45, 46, 47, 48]],

       [[49, 50, 51, 52],
        [53, 54, 55, 56],
        [57, 58, 59, 60],
        [61, 62, 63, 64]]])

In [174]:
book1.diagonal(offset=0, axis1=-3, axis2=-1)

array([[ 1, 18, 35, 52],
       [ 5, 22, 39, 56],
       [ 9, 26, 43, 60],
       [13, 30, 47, 64]])

In [175]:
matrix2 = np.zeros((4, 4))
matrix2

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [176]:
np.fill_diagonal(a=matrix2, val=1)

In [177]:
matrix2

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [178]:
np.diag([1, 2, 3, 4])

array([[1, 0, 0, 0],
       [0, 2, 0, 0],
       [0, 0, 3, 0],
       [0, 0, 0, 4]])

In [179]:
np.diag([1, 2, 3, 4], k=1)

array([[0, 1, 0, 0, 0],
       [0, 0, 2, 0, 0],
       [0, 0, 0, 3, 0],
       [0, 0, 0, 0, 4],
       [0, 0, 0, 0, 0]])

In [181]:
matrix1

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12],
       [13, 14, 15, 16]])

In [180]:
np.diag(matrix1)

array([ 1,  6, 11, 16])

In [ ]:
np.amax()