In [1]:
import numpy as np

In [2]:
np.__name__

'numpy'

In [3]:
np.__version__

'1.24.1'

In [4]:
np.__path__

['C:\\Users\\AppsLab\\mambaforge\\envs\\jupyterlab-cf\\Lib\\site-packages\\numpy']

In [5]:
? np.ndarray

Init signature:  np.ndarray(self, /, *args, **kwargs)
Docstring:     
ndarray(shape, dtype=float, buffer=None, offset=0,
        strides=None, order=None)

An array object represents a multidimensional, homogeneous array
of fixed-size items.  An associated data-type object describes the
format of each element in the array (its byte-order, how many bytes it
occupies in memory, whether it is an integer, a floating point number,
or something else, etc.)

Arrays should be constructed using `array`, `zeros` or `empty` (refer
to the See Also section below).  The parameters given here refer to
a low-level method (`ndarray(...)`) for instantiating an array.

For more information, refer to the `numpy` module and examine the
methods and attributes of an array.

Parameters
----------
(for the __new__ method; see Notes below)

shape : tuple of ints
    Shape of created array.
dtype : data-type, optional
    Any object that can be interpreted as a numpy data type.
buffer : object exposing buffer in

In [6]:
? np.array

Docstring:
array(object, dtype=None, *, copy=True, order='K', subok=False, ndmin=0,
      like=None)

Create an array.

Parameters
----------
object : array_like
    An array, any object exposing the array interface, an object whose
    __array__ method returns an array, or any (nested) sequence.
    If object is a scalar, a 0-dimensional array containing object is
    returned.
dtype : data-type, optional
    The desired data-type for the array.  If not given, then the type will
    be determined as the minimum type required to hold the objects in the
    sequence.
copy : bool, optional
    If true (default), then the object is copied.  Otherwise, a copy will
    only be made if __array__ returns a copy, if obj is a nested sequence,
    or if a copy is needed to satisfy any of the other requirements
    (`dtype`, `order`, etc.).
order : {'K', 'A', 'C', 'F'}, optional
    Specify the memory layout of the array. If object is not an array, the
    newly created array will be in C order (

In [7]:
list1 = [1, 2, 3, 4]
list1

[1, 2, 3, 4]

In [8]:
list1 = [1, 
         2, 
         3, 
         4]
list1

[1, 2, 3, 4]

In [9]:
array1 = np.array(object=[1, 2, 3, 4])
array1

array([1, 2, 3, 4])

In [10]:
arrayr = np.array([1, 2, 3, 4], ndmin=2)
arrayr

array([[1, 2, 3, 4]])

In [11]:
arrayr.size

4

In [12]:
arrayr.ndim

2

In [13]:
arrayr.shape

(1, 4)

In [14]:
array1.ndim

1

In [15]:
array1.shape

(4,)

In [16]:
arrayr.ndim

2

In [17]:
arrayr.shape

(1, 4)

In [18]:
column = [1, 2, 3, 4]

In [19]:
row = [column]
row

[[1, 2, 3, 4]]

In [20]:
array1_cols = array1.shape[0]
array1_cols

4

In [21]:
arrayr_rows = arrayr.shape[0]
arrayr_rows

1

In [22]:
arrayr_cols = arrayr.shape[1]
arrayr_cols

4

In [23]:
array1_cols = array1.shape[-1]
array1_cols

4

In [24]:
arrayr_rows = arrayr.shape[-1]
arrayr_rows

4

In [25]:
arrayr_cols = arrayr.shape[-2]
arrayr_cols

1

In [26]:
arrayc = np.array([1, 2, 3, 4], ndmin=2).T
arrayc

array([[1],
       [2],
       [3],
       [4]])

In [27]:
arrayc.size

4

In [28]:
arrayc.ndim

2

In [29]:
arrayc.shape

(4, 1)

In [30]:
array1.shape

(4,)

In [31]:
arrayr.shape

(1, 4)

In [32]:
arrayr.size

4

In [33]:
arrayr.ndim

2

In [34]:
arrayr.shape

(1, 4)

In [35]:
array1 = np.array([1, 2, 3, 4])
array1

array([1, 2, 3, 4])

In [36]:
array1.dtype

dtype('int32')

In [37]:
array1 = np.array([1., 2, 3, 4])
array1

array([1., 2., 3., 4.])

In [38]:
array1.dtype

dtype('float64')

In [39]:
array1 = np.array([1+2j, 2, 3, 4])
array1

array([1.+2.j, 2.+0.j, 3.+0.j, 4.+0.j])

In [40]:
array1.dtype

dtype('complex128')

In [41]:
array1 = np.array([True, False, False, False])
array1

array([ True, False, False, False])

In [42]:
array1.dtype

dtype('bool')

In [43]:
array1 = np.array([1, 2, 3, 4], dtype=float)
array1

array([1., 2., 3., 4.])

In [44]:
array1.dtype

dtype('float64')

In [45]:
matrix1 = np.array([[1, 2, 3],
                    [4, 5, 6]])
matrix1

array([[1, 2, 3],
       [4, 5, 6]])

In [46]:
matrix1.size

6

In [47]:
matrix1.ndim

2

In [48]:
matrix1.shape

(2, 3)

In [49]:
matrix2 = np.empty_like(prototype=matrix1)
matrix2

array([[626159536,       541,         0],
       [        0,         1,       541]])

In [50]:
matrix3 = np.zeros_like(a=matrix1)
matrix3

array([[0, 0, 0],
       [0, 0, 0]])

In [51]:
matrix4 = np.ones_like(a=matrix1)
matrix4

array([[1, 1, 1],
       [1, 1, 1]])

In [52]:
matrix5 = np.full_like(a=matrix1, fill_value=2)
matrix5

array([[2, 2, 2],
       [2, 2, 2]])

In [53]:
matrix2 = np.empty(shape=(4, 3))
matrix2

array([[1.14831011e-311, 2.47032823e-322, 0.00000000e+000],
       [0.00000000e+000, 1.16709769e-312, 1.58817677e-052],
       [4.97525587e-091, 6.75217017e-067, 2.36683617e+179],
       [8.60394332e-067, 3.99910963e+252, 1.90979636e-312]])

In [54]:
matrix3 = np.zeros(shape=(4, 3))
matrix3

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [55]:
matrix4 = np.ones(shape=(4, 3))
matrix4

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [56]:
matrix5 = np.full(shape=(4, 3), fill_value=4)
matrix5

array([[4, 4, 4],
       [4, 4, 4],
       [4, 4, 4],
       [4, 4, 4]])

In [57]:
book1 = np.array([[[1, 2,], 
                   [3, 4]],
                  
                  [[5, 6], 
                   [7, 8]],
                  
                  [[9, 10], 
                   [11, 12]]])
book1

array([[[ 1,  2],
        [ 3,  4]],

       [[ 5,  6],
        [ 7,  8]],

       [[ 9, 10],
        [11, 12]]])

In [58]:
book1.size

12

In [59]:
book1.ndim

3

In [60]:
book1.shape

(3, 2, 2)

In [61]:
it = book1.flat
it

In [62]:
next(it)

1

In [63]:
next(it)

2

In [64]:
next(it)

3

In [65]:
next(it)

4

In [66]:
next(it)

5

In [67]:
list(it)

[6, 7, 8, 9, 10, 11, 12]

In [68]:
it = book1.flat
it

In [69]:
array1 = np.array(list(it))
array1

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12])

In [70]:
book1.flatten()

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12])

In [71]:
array1 = book1.ravel()
array1

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12])

In [72]:
array1 = np.ravel(book1)
array1

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12])

In [73]:
booklist1 = [[[1, 2,], 
              [3, 4]],
                  
              [[5, 6], 
               [7, 8]],
                  
              [[9, 10], 
               [11, 12]]]

booklist1

[[[1, 2], [3, 4]], [[5, 6], [7, 8]], [[9, 10], [11, 12]]]

In [74]:
array1 = np.ravel(booklist1)
array1

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12])

In [75]:
list(array1)

[1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12]

In [76]:
array1.tolist()

[1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12]

In [77]:
booklist1 = [[[1, 2,], 
              [3, 4]],
                  
              [[5, 6], 
               [7, 8]],
                  
              [[9, 10], 
               [11, 12]]]

booklist1

[[[1, 2], [3, 4]], [[5, 6], [7, 8]], [[9, 10], [11, 12]]]

In [78]:
np.ravel(booklist1, order='F')

array([ 1,  5,  9,  3,  7, 11,  2,  6, 10,  4,  8, 12])

In [79]:
matrix1 = np.reshape(a=book1, newshape=(4, 3))
matrix1

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [10, 11, 12]])

In [80]:
matrix1 = book1.reshape((4,3))
matrix1

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [10, 11, 12]])