In [1]:
import numpy as np

In [2]:
matrix1 = np.arange(start=1, stop=17, step=1).reshape((4, 4))
matrix1

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12],
       [13, 14, 15, 16]])

In [3]:
dir(matrix1)

['T',
 '__abs__',
 '__add__',
 '__and__',
 '__array__',
 '__array_finalize__',
 '__array_function__',
 '__array_interface__',
 '__array_prepare__',
 '__array_priority__',
 '__array_struct__',
 '__array_ufunc__',
 '__array_wrap__',
 '__bool__',
 '__class__',
 '__class_getitem__',
 '__complex__',
 '__contains__',
 '__copy__',
 '__deepcopy__',
 '__delattr__',
 '__delitem__',
 '__dir__',
 '__divmod__',
 '__dlpack__',
 '__dlpack_device__',
 '__doc__',
 '__eq__',
 '__float__',
 '__floordiv__',
 '__format__',
 '__ge__',
 '__getattribute__',
 '__getitem__',
 '__getstate__',
 '__gt__',
 '__hash__',
 '__iadd__',
 '__iand__',
 '__ifloordiv__',
 '__ilshift__',
 '__imatmul__',
 '__imod__',
 '__imul__',
 '__index__',
 '__init__',
 '__init_subclass__',
 '__int__',
 '__invert__',
 '__ior__',
 '__ipow__',
 '__irshift__',
 '__isub__',
 '__iter__',
 '__itruediv__',
 '__ixor__',
 '__le__',
 '__len__',
 '__lshift__',
 '__lt__',
 '__matmul__',
 '__mod__',
 '__mul__',
 '__ne__',
 '__neg__',
 '__new__',
 '__o

In [4]:
str(matrix1)

'[[ 1  2  3  4]\n [ 5  6  7  8]\n [ 9 10 11 12]\n [13 14 15 16]]'

In [5]:
print(matrix1)

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]
 [13 14 15 16]]


In [6]:
repr(matrix1)

'array([[ 1,  2,  3,  4],\n       [ 5,  6,  7,  8],\n       [ 9, 10, 11, 12],\n       [13, 14, 15, 16]])'

In [7]:
matrix1

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12],
       [13, 14, 15, 16]])

In [8]:
? matrix1

Type:        ndarray
String form:
[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]
 [13 14 15 16]]
Length:      4
File:        c:\users\appslab\mambaforge\envs\jupyterlab-cf\lib\site-packages\numpy\__init__.py
Docstring:  
ndarray(shape, dtype=float, buffer=None, offset=0,
        strides=None, order=None)

An array object represents a multidimensional, homogeneous array
of fixed-size items.  An associated data-type object describes the
format of each element in the array (its byte-order, how many bytes it
occupies in memory, whether it is an integer, a floating point number,
or something else, etc.)

Arrays should be constructed using `array`, `zeros` or `empty` (refer
to the See Also section below).  The parameters given here refer to
a low-level method (`ndarray(...)`) for instantiating an array.

For more information, refer to the `numpy` module and examine the
methods and attributes of an array.

Parameters
----------
(for the __new__ method; see Notes below)

shape : tuple of ints
  

In [9]:
len(matrix1)

4

In [10]:
matrix1

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12],
       [13, 14, 15, 16]])

In [11]:
matrix2 = matrix1

In [12]:
matrix2[3, 3] = 25
matrix2

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12],
       [13, 14, 15, 25]])

In [13]:
matrix1 = np.arange(start=1, stop=17, step=1).reshape((4, 4))
matrix1

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12],
       [13, 14, 15, 16]])

In [14]:
from copy import copy, deepcopy

In [15]:
matrix2 = copy(matrix1)

In [16]:
matrix2[3, 3] = 25
matrix2

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12],
       [13, 14, 15, 25]])

In [17]:
matrix1

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12],
       [13, 14, 15, 16]])

In [18]:
matrix3 = np.copy(matrix1)

In [19]:
matrix4 = matrix1.copy()

In [20]:
list1 = [1, 'hello', 3.14]

In [21]:
dict1 = {'r': 'red', 'g': 'green', 'b': 'blue'}

In [22]:
mixed_array= np.array([list1, dict1, 'world', 2, 6.28], dtype=object)
mixed_array

array([list([1, 'hello', 3.14]), {'r': 'red', 'g': 'green', 'b': 'blue'},
       'world', 2, 6.28], dtype=object)

In [23]:
mixed_array2 = mixed_array.copy()

In [24]:
mixed_array2[0][0] = 4
mixed_array2

array([list([4, 'hello', 3.14]), {'r': 'red', 'g': 'green', 'b': 'blue'},
       'world', 2, 6.28], dtype=object)

In [25]:
mixed_array

array([list([4, 'hello', 3.14]), {'r': 'red', 'g': 'green', 'b': 'blue'},
       'world', 2, 6.28], dtype=object)

In [26]:
list1

[4, 'hello', 3.14]

In [27]:
from copy import deepcopy

In [28]:
list1 = [1, 'hello', 3.14]

In [29]:
dict1 = {'r': 'red', 'g': 'green', 'b': 'blue'}

In [30]:
mixed_array= np.array([list1, dict1, 'world', 2, 6.28], dtype=object)
mixed_array

array([list([1, 'hello', 3.14]), {'r': 'red', 'g': 'green', 'b': 'blue'},
       'world', 2, 6.28], dtype=object)

In [31]:
mixed_array2 = deepcopy(mixed_array)

In [32]:
mixed_array2[0][0] = 4
mixed_array2

array([list([4, 'hello', 3.14]), {'r': 'red', 'g': 'green', 'b': 'blue'},
       'world', 2, 6.28], dtype=object)

In [33]:
mixed_array

array([list([1, 'hello', 3.14]), {'r': 'red', 'g': 'green', 'b': 'blue'},
       'world', 2, 6.28], dtype=object)

In [34]:
list1

[1, 'hello', 3.14]

In [35]:
matrix1 = np.array([[1, 2, 3, 4],
                    [-5, -6, -7, -8],
                    [9, 10, 11, 12],
                    [-13, -14, -15, -16]])
matrix1

array([[  1,   2,   3,   4],
       [ -5,  -6,  -7,  -8],
       [  9,  10,  11,  12],
       [-13, -14, -15, -16]])

In [36]:
matrix2 = +matrix1
matrix2

array([[  1,   2,   3,   4],
       [ -5,  -6,  -7,  -8],
       [  9,  10,  11,  12],
       [-13, -14, -15, -16]])

In [37]:
matrix3 = -matrix1
matrix3

array([[ -1,  -2,  -3,  -4],
       [  5,   6,   7,   8],
       [ -9, -10, -11, -12],
       [ 13,  14,  15,  16]])

In [38]:
matrix4 = abs(matrix1)
matrix4

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12],
       [13, 14, 15, 16]])

In [39]:
matrix1 = np.array([[1, 2, 3, 4],
                    [-5, -6, -7, -8],
                    [9, 10, 11, 12],
                    [-13, -14, -15, -16]])
matrix1

array([[  1,   2,   3,   4],
       [ -5,  -6,  -7,  -8],
       [  9,  10,  11,  12],
       [-13, -14, -15, -16]])

In [40]:
matrix2 = abs(matrix1)
matrix2

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12],
       [13, 14, 15, 16]])

In [41]:
matrix3 = matrix1 + matrix2
matrix3

array([[ 2,  4,  6,  8],
       [ 0,  0,  0,  0],
       [18, 20, 22, 24],
       [ 0,  0,  0,  0]])

In [42]:
matrix1 = np.array([[1, 2, 3, 4],
                    [-5, -6, -7, -8],
                    [9, 10, 11, 12],
                    [-13, -14, -15, -16]])
matrix1

array([[  1,   2,   3,   4],
       [ -5,  -6,  -7,  -8],
       [  9,  10,  11,  12],
       [-13, -14, -15, -16]])

In [43]:
matrix2 = matrix1 + 4
matrix2

array([[  5,   6,   7,   8],
       [ -1,  -2,  -3,  -4],
       [ 13,  14,  15,  16],
       [ -9, -10, -11, -12]])

In [44]:
matrix1 = np.array([[1, 2, 3, 4],
                    [-5, -6, -7, -8],
                    [9, 10, 11, 12],
                    [-13, -14, -15, -16]])
matrix1

array([[  1,   2,   3,   4],
       [ -5,  -6,  -7,  -8],
       [  9,  10,  11,  12],
       [-13, -14, -15, -16]])

In [45]:
row = np.arange(start=0, stop=4, step=1)[np.newaxis, :]
row

array([[0, 1, 2, 3]])

In [46]:
matrix2 = matrix1 + row
matrix2

array([[  1,   3,   5,   7],
       [ -5,  -5,  -5,  -5],
       [  9,  11,  13,  15],
       [-13, -13, -13, -13]])

In [47]:
matrix1 = np.array([[1, 2, 3, 4],
                    [-5, -6, -7, -8],
                    [9, 10, 11, 12],
                    [-13, -14, -15, -16]])
matrix1

array([[  1,   2,   3,   4],
       [ -5,  -6,  -7,  -8],
       [  9,  10,  11,  12],
       [-13, -14, -15, -16]])

In [48]:
col = np.arange(start=0, stop=4, step=1)[:, np.newaxis]
col

array([[0],
       [1],
       [2],
       [3]])

In [49]:
matrix2 = matrix1 + col
matrix2

array([[  1,   2,   3,   4],
       [ -4,  -5,  -6,  -7],
       [ 11,  12,  13,  14],
       [-10, -11, -12, -13]])

In [50]:
vec = np.arange(start=0, stop=4, step=1)
vec

array([0, 1, 2, 3])

In [51]:
rowvec = np.arange(start=0, stop=4, step=1)[np.newaxis, :]
rowvec

array([[0, 1, 2, 3]])

In [52]:
colvec = np.arange(start=0, stop=4, step=1)[:, np.newaxis]
colvec

array([[0],
       [1],
       [2],
       [3]])

In [53]:
leftarray = np.array([5, 6], ndmin=2)
leftarray

array([[5, 6]])

In [54]:
rightarray = np.array([7, 8])[:, np.newaxis]
rightarray

array([[7],
       [8]])

In [55]:
leftarray.shape

(1, 2)

In [56]:
rightarray.shape

(2, 1)

In [57]:
leftarray.shape[-1] == rightarray.shape[0]

True

In [58]:
leftarray.shape[-1:] + rightarray.shape[:len(rightarray.shape)-1]

(2, 2)

In [59]:
leftarray @ rightarray

array([[83]])

In [60]:
np.dot(leftarray, rightarray)

array([[83]])

In [61]:
leftarray = np.array([5, 6])[:, np.newaxis]
leftarray

array([[5],
       [6]])

In [62]:
rightarray = np.array([7, 8], ndmin=2)
rightarray

array([[7, 8]])

In [63]:
leftarray @ rightarray

array([[35, 40],
       [42, 48]])

In [64]:
leftlist = [5, 6]

In [65]:
rightlist = [7, 8]

In [66]:
np.inner(leftlist, rightlist)

83

In [67]:
np.outer(leftlist, rightlist)

array([[35, 40],
       [42, 48]])

In [75]:
equations = np.array([[5, 6],
                      [3, 3]])
equations

array([[5, 6],
       [3, 3]])

In [76]:
results = np.array([83, 42])[:, np.newaxis]
results

array([[83],
       [42]])

In [86]:
inv_equations = np.linalg.inv(equations)
inv_equations

array([[-1.        ,  2.        ],
       [ 1.        , -1.66666667]])

In [83]:
inv_equations @ equations

array([[ 1.0000000e+00, -8.8817842e-16],
       [ 0.0000000e+00,  1.0000000e+00]])

In [89]:
np.identity(2)

array([[1., 0.],
       [0., 1.]])

In [88]:
np.eye(2)

array([[1., 0.],
       [0., 1.]])

In [85]:
coefficients = inv_equations @ results
coefficients

array([[ 1.],
       [13.]])

In [91]:
coefficients = np.linalg.solve(equations, results)
coefficients

array([[ 1.],
       [13.]])

In [77]:
coefficients = np.linalg.solve(equations, results)
coefficients

array([[ 1.],
       [13.]])

In [ ]:
a = np.array([[1, 2],
              [3, 1]])
b = np.array([11, 10])[:, np.newaxis]