In [3]:
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd

In [2]:
pd.__version__

'2.0.0'

In [4]:
xlist = [1, 2, 3, 4, 5]

In [5]:
xarray = np.array(xlist)

In [7]:
xarray = np.array([1, 2, 3, 4, 5])

In [82]:
xcol = np.array([1, 2, 3, 4, 5])[:, np.newaxis]

In [46]:
ycol = np.array([2, 4, 6, 8, 10])[:, np.newaxis]

In [80]:
zcol = np.array([4, 8, 12, 16, 20])[:, np.newaxis]

In [86]:
xarray

array([1, 2, 3, 4, 5])

In [85]:
xcol

array([[1],
       [2],
       [3],
       [4],
       [5]])

In [84]:
xseries = pd.Series(data=xarray, 
                    name='x',
                    dtype=int)

In [32]:
xseries

0    1
1    2
2    3
3    4
4    5
Name: x, dtype: int32

In [31]:
xseries = pd.Series(data=np.array([1, 2, 3, 4, 5]), 
                    name='x',
                    dtype=int)

In [33]:
xseries = pd.Series(data=[1, 2, 3, 4, 5], 
                    name='x',
                    dtype=int)

In [36]:
yseries = pd.Series(data=[2, 4, 6, 8, 10],
                    name='y',
                    dtype=int)

In [37]:
yseries

0     2
1     4
2     6
3     8
4    10
Name: y, dtype: int32

In [52]:
df = pd.DataFrame(data=xcol,
                  columns=['x'],
                  dtype=int)

In [87]:
matrix = np.concatenate((xcol, ycol, zcol), axis=-1)
matrix

array([[ 1,  2,  4],
       [ 2,  4,  8],
       [ 3,  6, 12],
       [ 4,  8, 16],
       [ 5, 10, 20]])

In [88]:
df = pd.DataFrame(data=matrix,
                  columns=['x', 'y', 'z'],
                  dtype=int)

In [89]:
df

x   y   z
0  1   2   4
1  2   4   8
2  3   6  12
3  4   8  16
4  5  10  20

In [90]:
df.dtypes

x    int32
y    int32
z    int32
dtype: object

In [91]:
types = {'x': int,
         'y': float,
         'z': str}

In [92]:
df.astype

<bound method NDFrame.astype of    x   y   z
0  1   2   4
1  2   4   8
2  3   6  12
3  4   8  16
4  5  10  20>

In [65]:
df = pd.DataFrame(data={'x': [1, 
                              2, 
                              3, 
                              4, 
                              5],
                        'y': [2, 
                              4, 
                              6, 
                              8, 
                              10]},
                  dtype=int)

In [64]:
df

x   y
0  1   2
1  2   4
2  3   6
3  4   8
4  5  10

In [66]:
df = pd.DataFrame(data={'x': [1, 2, 3, 4, 5],
                        'y': [2, 4, 6, 8, 10]},
                  dtype=int)

In [67]:
df

x   y
0  1   2
1  2   4
2  3   6
3  4   8
4  5  10

In [77]:
types = {'x': int,
         'y': float}

In [78]:
df = df.astype(types)
df

x     y
0  1   2.0
1  2   4.0
2  3   6.0
3  4   8.0
4  5  10.0

In [79]:
df.x.dtype

dtype('int32')

In [96]:
? df.astype

ValueError: The truth value of a DataFrame is ambiguous. Use a.empty, a.bool(), a.item(), a.any() or a.all().

In [97]:
? df.abs

ValueError: The truth value of a DataFrame is ambiguous. Use a.empty, a.bool(), a.item(), a.any() or a.all().

In [ ]:
np.array()

In [98]:
? pd.DataFrame

Init signature:
 pd.DataFrame(
    data=None,
    index: 'Axes | None' = None,
    columns: 'Axes | None' = None,
    dtype: 'Dtype | None' = None,
    copy: 'bool | None' = None,
) -> 'None'
Docstring:     
Two-dimensional, size-mutable, potentially heterogeneous tabular data.

Data structure also contains labeled axes (rows and columns).
Arithmetic operations align on both row and column labels. Can be
thought of as a dict-like container for Series objects. The primary
pandas data structure.

Parameters
----------
data : ndarray (structured or homogeneous), Iterable, dict, or DataFrame
    Dict can contain Series, arrays, constants, dataclass or list-like objects. If
    data is a dict, column order follows insertion-order. If a dict contains Series
    which have an index defined, it is aligned by its index. This alignment also
    occurs if data is a Series or a DataFrame itself. Alignment is done on
    Series/DataFrame inputs.

    If data is a list of dicts, column order follows